sudo: false
language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '16'
before_script:
  - npm prune
script:
  - npm run lint
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
