sudo: false
language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '10'
before_install:
  - npm i -g npm@^6.4.0
before_script:
  - npm prune
script:
  - npm run lint
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"